name: Auto Tag on Main Merge

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  auto-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract version from pubspec.yaml
        id: get_version
        run: |
          # Extract version from pubspec.yaml (format: x.y.z+build)
          VERSION=$(grep "^version:" pubspec.yaml | sed 's/version: *//' | sed 's/+.*//')
          BUILD_NUMBER=$(grep "^version:" pubspec.yaml | sed 's/.*+//')
          FULL_VERSION=$(grep "^version:" pubspec.yaml | sed 's/version: *//')

          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "build_number=$BUILD_NUMBER" >> $GITHUB_OUTPUT
          echo "full_version=$FULL_VERSION" >> $GITHUB_OUTPUT

          echo "Extracted version: $VERSION"
          echo "Build number: $BUILD_NUMBER"
          echo "Full version: $FULL_VERSION"

      - name: Check if tag already exists
        id: check_tag
        run: |
          if git tag -l | grep -q "^v${{ steps.get_version.outputs.version }}$"; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "Tag v${{ steps.get_version.outputs.version }} already exists"
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "Tag v${{ steps.get_version.outputs.version }} does not exist"
          fi

      - name: Create and push tag
        if: steps.check_tag.outputs.exists == 'false'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          # Create annotated tag with version info
          git tag -a "v${{ steps.get_version.outputs.version }}" -m "Release v${{ steps.get_version.outputs.version }} (Build: ${{ steps.get_version.outputs.build_number }})"

          # Push the tag
          git push origin "v${{ steps.get_version.outputs.version }}"

          echo "✅ Created and pushed tag: v${{ steps.get_version.outputs.version }}"

      - name: Create GitHub Release
        if: steps.check_tag.outputs.exists == 'false'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          release_name: Release v${{ steps.get_version.outputs.version }}
          body: |
            🚀 **QuranKu v${{ steps.get_version.outputs.version }}**

            **Build Number:** ${{ steps.get_version.outputs.build_number }}
            **Full Version:** ${{ steps.get_version.outputs.full_version }}

            This release was automatically created from the main branch.

            ### What's Changed
            - Auto-generated release from main branch merge

            **Full Changelog**: https://github.com/${{ github.repository }}/compare/v${{ steps.get_version.outputs.version }}...v${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false

      - name: Tag already exists
        if: steps.check_tag.outputs.exists == 'true'
        run: |
          echo "⚠️ Tag v${{ steps.get_version.outputs.version }} already exists. Skipping tag creation."
          echo "If you want to create a new tag, please bump the version in pubspec.yaml first."
