name: Build and Test

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        target: [ios --no-codesign, apk --debug]
        include:
          - target: ios --no-codesign
            os: ${{ vars.MACOSVERSIONRUN || 'macos-latest' }}
            platform: ios
          - target: apk --debug
            os: ubuntu-latest
            platform: android

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter Environment
        uses: ./.github/actions/setup-flutter-environment
        with:
          platform: ${{ matrix.platform }}
          setup-android: ${{ matrix.platform == 'android' }}
          setup-ios: ${{ matrix.platform == 'ios' }}
          install-ruby: "false"
        env:
          FIREBASE_OPTIONS: ${{ secrets.FIREBASE_OPTION_FILE }}
          FIREBASE_OPTIONS_DEBUG: ${{ secrets.FIREBASE_OPTION_FILE_DEBUG }}
          FIREBASE_ANDROID_JSON: ${{ secrets.GOOGLE_SERVICE_ANDROID_JSON_FILE }}
          FIREBASE_IOS_PLIST: ${{ secrets.GOOGLE_SERVICE_IOS_PLIST_FILE }}
          ENV_FILE: ${{ secrets.ENV_FILE }}

      - name: Run Tests
        run: flutter test --no-pub --coverage

      - name: Build Flutter App
        uses: ./.github/actions/build-flutter-app
        with:
          target: ${{ matrix.target }}
          platform: ${{ matrix.platform }}
