name: iOS Build & Deploy

on:
  workflow_dispatch:
    inputs:
      lane:
        description: "Fastlane lane"
        required: true
        default: "internal_patch"
        type: choice
        options:
          - internal_patch
          - internal_minor
          - internal_major
          - production_patch
          - production_minor
          - production_major

jobs:
  release-ios:
    uses: ./.github/workflows/release-app.yml
    with:
      platform: ios
      lane: ${{ github.event.inputs.lane }}
    secrets: inherit

  bump-version:
    needs: release-ios
    uses: ./.github/workflows/bump-version.yml
    with:
      lane: ${{ github.event.inputs.lane }}
    secrets: inherit
