name: Build Flutter

on:
  push:
    branches:
      - main
  pull_request:

permissions: read-all

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        target: ["apk --debug", "appbundle --debug", "ios --no-codesign"]
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Install iOS Simulator Runtime
        run: |
          sudo xcodebuild -downloadPlatform iOS

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "temurin"

      - name: Read Version Flutter
        id: read_fvm_config
        uses: juliangruber/read-file-action@v1.1.6
        with:
          path: ./.fvm/fvm_config.json

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{fromJson(steps.read_fvm_config.outputs.content).flutterSdkVersion}}

      - name: Check Flutter
        run: flutter doctor -v

      - name: Create Firebase Directory for iOS
        run: |
          mkdir -p ios/Runner/Firebase/Debug
          mkdir -p ios/Runner/Firebase/Release

      - name: Configure Firebase
        run: |
          echo "$FIREBASE_OPTIONS" | base64 --decode > lib/firebase_options.dart
          echo "$FIREBASE_ANDROID_JSON" | base64 --decode > android/app/google-services.json
          echo "$FIREBASE_IOS_PLIST" | base64 --decode > ios/Runner/GoogleService-Info.plist
          echo "$FIREBASE_IOS_PLIST" | base64 --decode > ios/Runner/Firebase/Debug/GoogleService-Info.plist
          echo "$FIREBASE_IOS_PLIST" | base64 --decode > ios/Runner/Firebase/Release/GoogleService-Info.plist
        env:
          FIREBASE_OPTIONS: ${{ secrets.FIREBASE_OPTION_FILE }}
          FIREBASE_ANDROID_JSON: ${{ secrets.GOOGLE_SERVICE_ANDROID_JSON_FILE }}
          FIREBASE_IOS_PLIST: ${{ secrets.GOOGLE_SERVICE_IOS_PLIST_FILE }}

      - name: Add .env file
        run: |
          echo "$ENV_FILE" | base64 --decode > .env
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}

      - name: Install packages
        run: flutter pub get

      - name: Run build-runner
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Run easy_localization
        run: flutter pub run easy_localization:generate -f keys -o locale_keys.g.dart --source-dir assets/translations

      - name: Build
        run: flutter build ${{ matrix.target }}

      - name: Install Cider
        run: dart pub global activate cider

      - name: Increment Build Number
        run: flutter pub global run cider bump build

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          message: "chore: bump build number (BOT)"
          github_token: ${{ secrets.TOKEN_GITHUB }}
